language: node_js
node_js:
  - lts/*
cache:
  yarn: true
  directories:
    - "node_modules"
install:
  - yarn
before_deploy:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  verbose: true
  on:
    branch: master